module Ordering
end

require_dependency 'ordering/add_item_to_basket'
require_dependency 'ordering/fake_number_generator'
require_dependency 'ordering/item_added_to_basket'
require_dependency 'ordering/item_removed_from_basket'
require_dependency 'ordering/number_generator'
require_dependency 'ordering/on_add_item_to_basket'
require_dependency 'ordering/on_remove_item_from_basket'
require_dependency 'ordering/on_set_order_as_expired'
require_dependency 'ordering/on_mark_order_as_paid'
require_dependency 'ordering/on_submit_order'
require_dependency 'ordering/order'
require_dependency 'ordering/order_expired'
require_dependency 'ordering/order_paid'
require_dependency 'ordering/order_line'
require_dependency 'ordering/order_submitted'
require_dependency 'ordering/remove_item_from_basket'
require_dependency 'ordering/set_order_as_expired'
require_dependency 'ordering/mark_order_as_paid'
require_dependency 'ordering/submit_order'
