requires:
  - ./test/test_helper
integration: minitest
usage: opensource
coverage_criteria:
  process_abort: true
matcher:
  subjects:
    - Fulfillment*
  ignore:
    - Fulfillment::Test*
    - Fulfillment::NumberGenerator*
    - Fulfillment::Configuration#call
    - Fulfillment::Configuration#initialize
