requires:
  - ./test/test_helper
integration: minitest
coverage_criteria:
  process_abort: true
matcher:
  subjects:
    - Payments*
  ignore:
    - Payments::Payment#authorized?
    - Payments::Test*
    - Payments::Configuration#call
