---
includes:
  - test
integration: minitest
mutation_timeout: 10.0
coverage_criteria:
  timeout: true
  process_abort: true
requires:
  - ./lib/infra.rb
matcher:
  subjects:
    - Infra*
  ignore:
    - Infra::Event*
    - Infra::Command*
    - Infra::AggregateRootRepository*
    - Infra::TestPlumbing*
    - Infra::NoEvent*
    - Infra::EventStore*
    - Infra::Mapper*
    - Infra::Process*
    - Infra::EventHandler*
