requires:
  - ./test/test_helper
integration: minitest
usage: opensource
coverage_criteria:
  process_abort: true
matcher:
  subjects:
    - Processes*
  ignore:
    - Processes::Configuration*
    - Processes::OrderConfirmation#stream_name
    - Processes::Test*
    - Processes::ReleasePaymentProcess*
    - Processes::OrderItemInvoicingProcess*
    - Processes::SyncShipmentFromPricing*
    - Processes::SyncInventoryFromOrdering*
    - Processes::NotifyPaymentsAboutOrderValue*
    - Processes::ThreePlusOneFree*
    - Processes::DetermineVatRatesOnOrderPlaced*
