---
includes:
  - test
integration: minitest
mutation_timeout: 10.0
coverage_criteria:
  timeout: true
  process_abort: true
requires:
  - ./config/environment
matcher:
  subjects:
    - Orders*
    - ClientOrders*
  ignore:
    - Orders::Configuration#call
    - Orders::Configuration#change_product_price
    - ClientOrders::Configuration#call
    - ClientOrders::Configuration#mark_as_submitted
    - ClientOrders::Configuration#subscribe_and_link_to_stream
    - ClientOrders::Configuration#link_to_stream
    - ClientOrders::Configuration#with_order
    - ClientOrders::OrdersList*
    - ClientOrders::RemoveItemFromOrder*
    - ClientOrders::AddItemToOrder*
