---
mutation:
  operators: light
  timeout: 10.0
includes:
  - test
integration:
  name: minitest
jobs: 4
usage: opensource
coverage_criteria:
  timeout: true
  process_abort: true
requires:
  - ./config/environment
matcher:
  subjects:
    - Orders*
    - ClientOrders*
    - Processes*
  ignore:
    - Orders::Configuration#call
    - Orders::Broadcaster*
    - Orders::AddItemToOrder#broadcast_to_ui
    - Orders::RemoveItemFromOrder#broadcast_to_ui
    - Orders::SubmitService#submit_order
    - ClientOrders::Configuration#call
    - ClientOrders::Configuration#mark_as_submitted
    - ClientOrders::Configuration#subscribe_and_link_to_stream
    - ClientOrders::Configuration#link_to_stream
    - ClientOrders::Configuration#with_order
    - ClientOrders::Rendering::OrdersList*
    - ClientOrders::RemoveItemFromOrder*
    - ClientOrders::AddItemToOrder#show_remove_item_button
    - ClientOrders::AddItemToOrder#remove_button_html
    - ClientOrders::AddItemToOrder#broadcast_to_ui
    - ClientOrders::AddItemToOrder#broadcast_update
    - ClientOrders::AddItemToOrder#call
    - ClientOrders::ProductHandlers::ChangeProductName*
    - ClientOrders::ProductHandlers::ChangeProductPrice*
    - ClientOrders::ProductHandlers::RegisterProduct*
    - ClientOrders::Rendering::ShowOrder*
    - ClientOrders::Rendering::EditOrder*
    - Processes::Configuration*
    - Processes::OrderConfirmation#stream_name
    - Processes::Test*
    - Processes::ReleasePaymentProcess*
    - Processes::MoneySplitter*
    - Processes::SyncShipmentFromPricing*
    - Processes::SyncInventoryFromOrdering*
    - Processes::NotifyPaymentsAboutOrderValue*
    - Processes::WelcomeMessageProcess*
    - Processes::TotalOrderValue#fetch_id
    - Processes::InvoiceGeneration#fetch_id
