#!/bin/sh

# script/server: Launch the application and any extra required processes
# locally.

set -e

cd "$(dirname "$0")/.."

test -z "$HANAMI_ENV" && HANAMI_ENV='development'

if ! command -v overmind > /dev/null; then
  echo "You must install Overmind to use this script. See:"
  echo " . https://github.com/DarthSim/overmind#installation"
  exit 1
fi

# Boot the app and any other necessary processes
exec env OVERMIND_PORT=3000 overmind start -f Procfile.dev
