requires:
  - ./test/test_helper
integration: minitest
usage: opensource
coverage_criteria:
  process_abort: true
matcher:
  subjects:
    - Pricing*
  ignore:
    - Pricing::Configuration*
    - Pricing::Test*
    - Pricing::MakeProductFreeForOrderHandler*
    - Pricing::RemoveFreeProductFromOrderHandler*
    - Pricing::Offer::List*
    - Pricing::Offer::Product*
    - Pricing::Offer::FreeProduct*
    - Pricing::Offer#make_product_free
    - Pricing::Offer#remove_free_product
