requires:
  - ./test/test_helper
integration: minitest
usage: opensource
coverage_criteria:
  process_abort: true
matcher:
  subjects:
    - Pricing*
  ignore:
    - Pricing::Configuration*
    - Pricing::Test*
    - Pricing::OnCalculateTotalValue#call
    - Pricing::OnCalculateTotalValue#calculate_sub_amounts
    - Pricing::Offer#make_free_product
    - Pricing::Offer#remove_free_product
    - Pricing::Offer::List#set_free
    - Pricing::Offer::List#restore_nonfree
