requires:
  - ./test/test_helper
integration: minitest
coverage_criteria:
  process_abort: true
matcher:
  subjects:
    - Pricing*
  ignore:
    - Pricing::SetPriceHandler#call
    - Pricing::Configuration*
    - Pricing::OnCalculateTotalValue#last_discount_order_event
    - Pricing::SetPercentageDiscountHandler#last_event
    - Pricing::Order#remove_item
    - Pricing::OnRemoveItemFromBasket#call
    - Pricing::SetPercentageDiscountHandler#initialize
    - Pricing::ResetPercentageDiscountHandler#initialize
    - Pricing::ChangePercentageDiscountHandler#initialize
    - Pricing::OnRemoveItemFromBasket#initialize
    - Pricing::Discounts::NoPercentageDiscount#discount
    - Pricing::Test*
