includes:
  - test
requires:
  - ./config/environment
integration: minitest
usage: opensource
coverage_criteria:
  timeout: true
  process_abort: true
matcher:
  subjects:
    - Processes*
    - Applications*
    - PolicyList*
    - ClaimList*
  ignore:
    - Processes::Configuration#call
    - Applications::Configuration#call
    - Applications::Application*
    - PolicyList::Configuration#call
    - PolicyList::Policy*
    - ClaimList::Configuration#call
    - ClaimList::Claim*
