require "infra"
require_relative "crm/commands/promote_customer_to_vip"
require_relative "crm/commands/register_customer"
require_relative "crm/commands/assign_customer_to_order"
require_relative "crm/commands/register_contact"
require_relative "crm/commands/set_contact_email"
require_relative "crm/commands/set_contact_phone"
require_relative "crm/commands/set_contact_linkedin_url"
require_relative "crm/events/customer_promoted_to_vip"
require_relative "crm/events/customer_registered"
require_relative "crm/events/customer_assigned_to_order.rb"
require_relative "crm/events/contact_registered"
require_relative "crm/events/contact_email_set"
require_relative "crm/events/contact_phone_set"
require_relative "crm/events/contact_linkedin_url_set"
require_relative "crm/customer_service"
require_relative "crm/customer"
require_relative "crm/order_service"
require_relative "crm/order"
require_relative "crm/contact_service"
require_relative "crm/contact"
require_relative "crm/commands/register_company"
require_relative "crm/commands/set_company_linkedin_url"
require_relative "crm/events/company_registered"
require_relative "crm/events/company_linkedin_url_set"
require_relative "crm/company_service"
require_relative "crm/company"
require_relative "crm/commands/create_pipeline"
require_relative "crm/commands/add_stage_to_pipeline"
require_relative "crm/commands/remove_stage_from_pipeline"
require_relative "crm/events/pipeline_created"
require_relative "crm/events/stage_added_to_pipeline"
require_relative "crm/events/stage_removed_from_pipeline"
require_relative "crm/pipeline_service"
require_relative "crm/pipeline"
require_relative "crm/commands/create_deal"
require_relative "crm/commands/set_deal_value"
require_relative "crm/commands/set_deal_expected_close_date"
require_relative "crm/commands/move_deal_to_stage"
require_relative "crm/events/deal_created"
require_relative "crm/events/deal_value_set"
require_relative "crm/events/deal_expected_close_date_set"
require_relative "crm/events/deal_moved_to_stage"
require_relative "crm/deal_service"
require_relative "crm/deal"

module Crm
  class Configuration

    def call(event_store, command_bus)
      command_bus.register(RegisterCustomer, OnRegistration.new(event_store))
      command_bus.register(PromoteCustomerToVip, OnPromoteCustomerToVip.new(event_store))
      command_bus.register(AssignCustomerToOrder, OnSetCustomer.new(event_store))
      command_bus.register(RegisterContact, OnRegisterContact.new(event_store))
      command_bus.register(SetContactEmail, OnSetContactEmail.new(event_store))
      command_bus.register(SetContactPhone, OnSetContactPhone.new(event_store))
      command_bus.register(SetContactLinkedinUrl, OnSetContactLinkedinUrl.new(event_store))
      command_bus.register(RegisterCompany, OnRegisterCompany.new(event_store))
      command_bus.register(SetCompanyLinkedinUrl, OnSetCompanyLinkedinUrl.new(event_store))
      command_bus.register(CreatePipeline, OnCreatePipeline.new(event_store))
      command_bus.register(AddStageToPipeline, OnAddStageToPipeline.new(event_store))
      command_bus.register(RemoveStageFromPipeline, OnRemoveStageFromPipeline.new(event_store))
      command_bus.register(CreateDeal, OnCreateDeal.new(event_store))
      command_bus.register(SetDealValue, OnSetDealValue.new(event_store))
      command_bus.register(SetDealExpectedCloseDate, OnSetDealExpectedCloseDate.new(event_store))
      command_bus.register(MoveDealToStage, OnMoveDealToStage.new(event_store))
    end
  end
end
