requires:
  - ./test/test_helper
integration: minitest
coverage_criteria:
  process_abort: true
matcher:
  subjects:
    - Taxes*
  ignore:
    - Taxes::Test*
    - Taxes::Configuration*
    - Taxes::VatRateCatalog#vat_rate_for