includes:
  - test
requires:
  - ./config/environment
integration: minitest
usage: opensource
coverage_criteria:
  timeout: true
  process_abort: true
matcher:
  subjects:
    - PublicFeed*
    - Accounts*
    - Follows*
    - PersonalTimeline*
    - Profile*
    - TimelineDeliveryProcess*
  ignore:
    - PublicFeed::Configuration#call
    - Accounts::Configuration#call
    - Follows::Configuration#call
    - PersonalTimeline::Configuration#call
    - Profile::Configuration#call
