---
environment_variables:
  RAILS_ENV: test
mutation:
  operators: light
  timeout: 10.0
includes:
  - test
integration:
  name: minitest
usage: opensource
coverage_criteria:
  timeout: true
  process_abort: true
requires:
  - ./config/environment
matcher:
  subjects:
    - Coupons*
    - Orders*
    - OrderHeader*
    - ClientOrders*
    - Processes*
    - Invoices*
    - Shipments*
    - VatRates*
    - Deals*
  ignore:
    - Coupons::Configuration#call
    - Orders::Configuration#call
    - Orders::Configuration#broadcast_order_state_change
    - OrderHeader::Configuration#call
    - Invoices::Configuration#call
    - Orders::Broadcaster*
    - Orders::AddItemToOrder#broadcast_to_ui
    - Orders::RemoveItemFromOrder#broadcast_to_ui
    - Orders::SubmitService#submit_order
    - ClientOrders::Configuration#call
    - ClientOrders::Configuration#mark_as_submitted
    - ClientOrders::Configuration#subscribe_and_link_to_stream
    - ClientOrders::Configuration#link_to_stream
    - ClientOrders::Configuration#with_order
    - ClientOrders::AddItemToOrder#call
    - ClientOrders::AddItemToOrder#broadcast_to_ui
    - ClientOrders::AddItemToOrder#broadcast_update
    - ClientOrders::AddItemToOrder#show_remove_item_button
    - ClientOrders::AddItemToOrder#remove_button_html
    - ClientOrders::RemoveItemFromOrder#call
    - ClientOrders::RemoveItemFromOrder#broadcast_to_ui
    - ClientOrders::RemoveItemFromOrder#broadcast_update
    - ClientOrders::RemoveItemFromOrder#zero_quantity?
    - ClientOrders::RemoveItemFromOrder#event_store
    - ClientOrders::Rendering::OrdersList*
    - ClientOrders::Rendering::ShowOrder*
    - ClientOrders::Rendering::EditOrder*
    - Processes::Configuration*
    - Processes::OrderConfirmation#stream_name
    - Processes::Test*
    - Processes::Invoices::MoneySplitter*
    - Processes::SyncShipmentFromPricing*
    - Processes::SyncInventoryFromOrdering*
    - Processes::NotifyPaymentsAboutOrderValue*
    - Processes::WelcomeMessageProcess*
    - Processes::TotalOrderValue#fetch_id
    - Processes::InvoiceGeneration#fetch_id
    - Processes::ApplyTimePromotion#initialize
    - Deals::Configuration#call
    - Deals::Rendering::DealsBoard*
