source "https://rubygems.org"

ruby '~> 3.4.9'

gem "rails", "~> 8.1.0"
gem "pg", "~> 1.5"
gem "puma"
gem "bootsnap", ">= 1.9.2", require: false
gem "honeybadger"
gem "skylight"
gem "tailwindcss-rails", "~> 4.0"
gem "kaminari"
gem "sprockets-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "importmap-rails", "~> 2.0"
gem "rails_event_store",  ">= 3.0", "< 4.0"
gem 'arbre'

group :development do
  gem "listen", "~> 3.3"
  gem "herb"
  gem "bundler-audit"
  gem "ruby_event_store-cli"
end

group :development, :test do
  gem "byebug", platforms: %i[mri mingw x64_mingw]
  gem "dotenv-rails"
end

group :test do
  eval_gemfile "../../infra/Gemfile.test"
end

gem "infra", path: "../../infra"
gem "ruby_event_store-process_manager",
  git: "https://github.com/RailsEventStore/rails_event_store.git",
  ref: "ac9e73b69bc0",
  glob: "contrib/ruby_event_store-process_manager/*.gemspec",
  require: "ruby_event_store/process_manager"

gem "tzinfo-data"

gem "judoscale-rails"
