source "https://rubygems.org"

ruby '~> 3.4.6'

gem "rails", "~> 8.0.0"
gem "pg", "~> 1.5"
gem "puma"
gem "bootsnap", ">= 1.9.2", require: false
gem "honeybadger"
gem "skylight"
gem "tailwindcss-rails", "~> 2.6.0"
gem "kaminari"
gem "sprockets-rails"
gem "turbo-rails"
gem "stimulus-rails"
gem "importmap-rails", "~> 1.1"
gem "rails_event_store",  ">= 2.15.0", "< 3.0"
gem 'arbre'

group :development do
  gem "listen", "~> 3.3"
  gem "herb"
  gem "bundler-audit"
end

group :development, :test do
  gem "byebug", platforms: %i[mri mingw x64_mingw]
  gem "dotenv-rails"
end

group :test do
  eval_gemfile "../../infra/Gemfile.test"
end

gem "infra", path: "../../infra"

gem "tzinfo-data"
