requires:
  - ./test/test_helper
integration: minitest
usage: opensource
coverage_criteria:
  process_abort: true
matcher:
  subjects:
    - Todo*
  ignore:
    - Todo::Test*
    - Todo::AddTaskHandler#task_stream
    - Todo::Todo#initialize