includes:
  - test
requires:
  - ./config/environment
integration: minitest
usage: opensource
coverage_criteria:
  timeout: true
  process_abort: true
matcher:
  subjects:
    - Companies*
    - Contacts*
    - Pipelines*
    - Deals*
  ignore:
    - Companies::Company
    - Companies::Configuration#call
    - Contacts::Contact
    - Contacts::Configuration#call
    - Pipelines::Pipeline
    - Pipelines::Stage
    - Pipelines::Configuration#call
    - Pipelines.stages_for
    - Deals::Deal
    - Deals::Configuration#call
    - Deals.for_pipeline
