name: inventory
on:
  push:
  pull_request:
    types: [opened, reopened]
jobs:
  test:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    env:
      WORKING_DIRECTORY: ecommerce/inventory
    services:
      postgres_11:
        image: postgres:11
        env:
          POSTGRES_DB: cqrs-es-sample-with-res_test
          POSTGRES_PASSWORD: secret
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby-2.7.4
          bundler-cache: true
          working-directory: ${{ env.WORKING_DIRECTORY }}
      - run: make test
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_COLOR: ${{ job.status }}
  mutate:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
    env:
      WORKING_DIRECTORY: ecommerce/inventory
    services:
      postgres_11:
        image: postgres:11
        env:
          POSTGRES_DB: cqrs-es-sample-with-res_test
          POSTGRES_PASSWORD: secret
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby-2.7.4
          bundler-cache: true
          working-directory: ${{ env.WORKING_DIRECTORY }}
      - run: make mutate
        working-directory: ${{ env.WORKING_DIRECTORY }}
      - uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
