name: pricing
on:
  pull_request:
    paths:
      - "ecommerce/pricing/**"
      - ".github/workflows/pricing.yml"
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby-3.3.7
          bundler-cache: true
          working-directory: ecommerce/pricing
      - run: make -C ecommerce/pricing test
