name: pricing
on:
  push:
  pull_request:
    types: [opened, reopened]
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby-3.4.6
          bundler-cache: true
          working-directory: ecommerce/pricing
      - run: make -C ecommerce/pricing test
